package graph

// List from https://graphviz.gitlab.io/_pages/doc/info/colors.html plus some trimming of the light colors.

var colors = []string{"aqua", "aquamarine",
	"blanchedalmond", "blue",
	"blueviolet", "brown", "burlywood", "cadetblue", "chartreuse",
	"chocolate", "coral", "cornflowerblue", "crimson",
	"cyan", "darkblue", "darkcyan", "darkgoldenrod", "darkgray",
	"darkgreen", "darkgrey", "darkkhaki", "darkmagenta", "darkolivegreen",
	"darkorange", "darkorchid", "darkred", "darksalmon", "darkseagreen",
	"darkslateblue", "darkslategray", "darkslategrey", "darkturquoise", "darkviolet",
	"deeppink", "deepskyblue", "dimgray", "dimgrey", "dodgerblue",
	"firebrick", "forestgreen", "fuchsia", "gainsboro",
	"gold", "goldenrod", "gray", "grey",
	"green", "greenyellow", "hotpink", "indianred",
	"indigo", "khaki", "lavender", "lavenderblush",
	"lawngreen", "lemonchiffon", "lightblue", "lightcoral", "lightcyan",
	"lightgoldenrodyellow", "lightgray", "lightgreen", "lightgrey", "lightpink",
	"lightsalmon", "lightseagreen", "lightskyblue", "lightslategray", "lightslategrey",
	"lightsteelblue", "lightyellow", "lime", "limegreen",
	"linen",
	"magenta", "maroon", "mediumaquamarine", "mediumblue", "mediumorchid",
	"mediumpurple", "mediumseagreen", "mediumslateblue", "mediumspringgreen", "mediumturquoise",
	"mediumvioletred", "midnightblue", "mistyrose", "moccasin",
	"navajowhite", "navy", "oldlace", "olive", "olivedrab",
	"orange", "orangered", "orchid", "palegoldenrod", "palegreen",
	"paleturquoise", "palevioletred", "papayawhip", "peachpuff", "peru",
	"pink", "plum", "powderblue", "purple", "red",
	"rosybrown", "royalblue", "saddlebrown", "salmon", "sandybrown",
	"seagreen", "sienna", "skyblue",
	"slateblue", "slategray", "slategrey", "springgreen",
	"steelblue", "tan", "teal", "thistle", "tomato",
	"turquoise", "violet", "wheat",
	"yellow", "yellowgreen"}
