name: Code Style

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:

  lint:
    name: Lint
    runs-on: ubuntu-latest

    env:
      GOPATH: ${{ github.workspace }}

    steps:

    - name: Set up Go 1.16.x
      uses: actions/setup-go@v2
      with:
        go-version: 1.16.x

    - name: Check out code onto GOPATH
      uses: actions/checkout@v2

# TODO: add pretter step

    - name: Go Format
      shell: bash
      run: |
        gofmt -s -w $(find -path './vendor' -prune -o -path './third_party' -prune -o -type f -name '*.go' -print)

    - name: Verify
      shell: bash
      run: |
        if [[ $(git diff-index --name-only HEAD --) ]]; then
            echo "Found diffs in:"
            git diff-index --name-only HEAD --
            echo "${{ github.repository }} is out of style. Please run go fmt."
            exit 1
        fi
        echo "${{ github.repository }} is formatted correctly."
